filme/urls.py
# Definindo a url da homepage:

from django.urls import path, reverse_lazy
# Importando o objeto homepage
from .views import Homepage, Homefilmes, Detalhesfilme, Pesquisafilme, Paginaperfil, Criarconta, Pag_Form_Prod, Pag_Producao, Pag_Teste, dashboard, pagina, SuaView
from django.contrib.auth import views as auth_view

from django.urls import path
from .views import SuaView

app_name = 'filme'

urlpatterns = [
    # Chamando a função da View
    path('', Homepage.as_view(), name='homepage'),
    path('pag_form_prod/', Pag_Form_Prod.as_view(), name='pag_form_prod'),

    path('sua_view/', SuaView.as_view(), name='sua_view'),

    path('dashboard/', dashboard, name='dashboard'),
    path('pagina/', pagina, name='pagina'),
    path('pag_producao/', Pag_Producao.as_view(), name='pag_producao'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('pag_teste/', Pag_Teste.as_view(), name='pag_teste'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html',
                                                             success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),
]

hashflix/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
# Incluindo o link do endereço da pagina do site que deseja exibir o app:
    path('', include('filme.urls', namespace='filme')),
]
# Adicionando na lista a configuração de link das imagens
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.

# Criando a classe filme

LISTA_CATEGORIAS = (
    ("ANALISES", "Análises"),
    ("PROGRAMACAO", "Programação"),
    ("APRESENTACAO", "Apresentação"),
    ("OUTROS", "Outros"),
)

class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    vizualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    # Classe para trazer um nome desejado da classe:
    def __str__(self):
        return self.titulo


class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo


class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms
from datetime import timezone
import time


class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)




from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field


class Formulario_da_form_prod(forms.Form):

    # opcoes_setor = [
    #     ('', ''),
    #     ('laminacao', 'Laminação'),
    #     ('forjaria', 'Forjaria'),
    #     ('dobra', 'Dobra'),
    #     ('luxor', 'Luxor'),
    # ]

    opcoes_maquina = [
        ('', ''),
        ('LX-01', 'LX-01'),
        ('LR-04', 'LR-04'),
        ('LR-05', 'LR-05'),
        # ('DC-04', 'DC-04'),
        # ('DS-03', 'DS-03'),
        # ('DW-0', 'DW-02'),
        # ('DW-03', 'DW-03'),
    ]

    # frm_setor_selecionado = forms.ChoiceField(choices=opcoes_setor, widget=forms.Select, label="Setor")
    frm_maquina_selecionada = forms.ChoiceField(choices=opcoes_maquina, widget=forms.Select, label="Máquina")

    # frm_data_inicio = forms.CharField(max_length=15)
    frm_data_inicio = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), initial=(time.strftime("%Y-%m-%d")), label="Data Início")
    frm_hora_inicio = forms.CharField(max_length=5, label="Hora Início")
    # frm_data_fim = forms.CharField(max_length=15)
    frm_data_fim = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), initial=(time.strftime("%Y-%m-%d")), label="Data Fim")
    frm_hora_fim = forms.CharField(max_length=5, label="Hora Fim")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Div(
            Div('frm_maquina_selecionada', css_class='col-md-4'),
            Div('frm_data_inicio', 'frm_hora_inicio', css_class='col-md-4'),
            Div('frm_data_fim', 'frm_hora_fim', css_class='col-md-4'),
            css_class='row'
        )







class Formulario_especificar_paradas(forms.Form):

    Motivo = forms.CharField(max_length=15)
    Causa_e_Solucao = forms.CharField(max_length=30)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Div(
            Div('Motivo', css_class='col-md-6'),
            Div('Causa_e_Solucao', css_class='col-md-6'),
            css_class='row'
        )





class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

filme/views.py
from django.shortcuts import render, redirect, reverse
from .models import Filme, Usuario
from .forms import CriarContaForm, FormHomepage, Formulario_da_form_prod, Formulario_especificar_paradas
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
# Para poder importar do SQLite:
from .models import Filme
import time
from datetime import datetime, timedelta
from .obj_usar_resumo import Trazer_Dados
from .obj_maquinas_tabelas2 import Maquinas_Tabelas
from .obj_contabilizar_HH_MM_SS import Contabilizar_HH_MM_SS
from .obj_tempo_anterior_parado import Tempo_Anterior_Parado
from .obj_conexoes_bco_dados import Conexoes_SQL

# import locale
# locale.setlocale(locale.LC_ALL, 'pt_BR.utf-8')


class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('filme:homefilmes')# Redireciona para a homefilmes
        else:
            return super().get(request, *args, **kwargs)# Redireciona para a homepage

    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('filme:login')
        else:
            return reverse('filme:criarconta')


class Homefilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    model = Filme
    # object_list -> lista de itens do modelo


# class Pag_Teste(LoginRequiredMixin, ListView):
#     template_name = "pag_teste.html"
#     model = Filme
#
#     def valores(self):
#         context = {}
#         context['lista'] = str("texto1")
#
#         return render(self.request, 'pag_teste.html', context)


class Pag_Teste(View):
    form_class = Formulario_especificar_paradas

    def get(self, request):
        maquina = request.GET.get('maq')
        data_ini = request.GET.get('dt_in')
        hora_ini = request.GET.get('hr_in')
        data_fim = request.GET.get('dt_fi')
        hora_fim = request.GET.get('hr_fi')

        context = {}
        context['lista'] = [maquina, data_ini, hora_ini, data_fim, hora_fim]

        # Código para conseguir lista de todas as paradas no periodo:
        # Extraindo lista com todos os valores da tabela resumo:
        dados = Trazer_Dados('setor_selecionado', maquina, data_ini, hora_ini, data_fim, hora_fim)
        lista = dados.lista_valores()
        print("lista:", lista)
        # Refazendo a lista com os indices e pegando apenas os dados de paradas necessários:
        lista_paradas = [elemento[2:-5] for elemento in lista if elemento[2] != '' and
                         elemento[2] is not None and
                         elemento[6] == None]
        lista_paradas.reverse()# Invertendo as posições dos itens
        context['lista_paradas'] = lista_paradas
        # print("lista_paradas:", lista_paradas)

        lista_formatada_paradas = []
        for i in lista_paradas:
            lista_formatada_paradas.append(f"Parada e Retorno: {i[0]} {i[1]} a {i[2]} {i[3]}")
        context['lista_formatada_paradas'] = lista_formatada_paradas

        return render(request, 'pag_teste.html', context)








    # def post(self, request):
    #     # Lógica para lidar com requisições POST
    #     context = {}
    #     context['lista'] = str("texto1")
    #     return render(request, 'pag_teste.html', context)















# class Pag_Form_Prod(FormView):
#     template_name = "pag_form_prod.html"
#     model = Formulario_da_form_prod
#     # object_list -> lista de itens do modelo


# class Pag_Form_Prod(FormView):
#     template_name = "pag_form_prod.html"
#     form_class = Formulario_da_form_prod
#
#     def form_valid(self, form):
#         # Lógica para processar o formulário válido aqui
#         return redirect('filme:pag_producao')
#
#         # return super().form_valid(form)
#
#     # def redireciona(self):
#     #     return redirect('filme:homefilmes')




class Pag_Form_Prod(LoginRequiredMixin, FormView):
    template_name = "pag_form_prod.html"
    form_class = Formulario_da_form_prod

    def form_valid(self, form):
        context = {}

        context.update(Mostra_valores_atualizados().dados(form.cleaned_data['frm_maquina_selecionada'], form.cleaned_data['frm_data_inicio'].strftime("%d/%m/%Y"), form.cleaned_data['frm_hora_inicio'], form.cleaned_data['frm_data_fim'].strftime("%d/%m/%Y"), form.cleaned_data['frm_hora_fim']))
        print(context.keys())
        print(context['mostrar_cod_maquina'])

        return render(self.request, 'pag_producao.html', context)















# class Pag_Form_Prod(FormView):
#     template_name = "pag_form_prod.html"
#     form_class = Formulario_da_form_prod
#
#     def form_valid(self, form):
#         # Lógica para processar o formulário válido aqui
#         return redirect('filme:pag_producao')










class Pag_Producao(LoginRequiredMixin, ListView):
    template_name = "pag_producao.html"
    model = Filme


class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilme.html"
    model = Filme
    # object -> 1º item do nosso modelo

    def get(self, request, *args, **kwargs):
        # Contabilizar uma visualização
        filme = self.get_object()
        filme.vizualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs) # Redireciona o usuario para a url final

    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self).get_context_data(**kwargs)


        filmes_relacionados = self.model.objects.filter(categoria=self.get_object().categoria)
        context["filmes_relacionados"] = filmes_relacionados
        return context


class Pesquisafilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = self.model.objects.filter(titulo__icontains=termo_pesquisa)
            return object_list
        else:
            return None


class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    field = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('filme:homefilmes')


class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('filme:login')

# # Create your views here.
# # Esta função vai indicar qual é o arquivo html a ser exibido
# def homepage(request):
#     return render(request, "homepage.html")
#
# def homefilmes(request):
#     context = {}
#     lista_filmes = Filme.objects.all()
#     context['lista_filmes'] = lista_filmes
#     return render(request, "homefilmes.html", context)











class Mostra_valores_atualizados:
    def __init__(self):
        pass
    def dados(self, maquina_selecionada, data_inicio, hora_inicio, data_fim, hora_fim):
        self.maquina_selecionada = maquina_selecionada

        self.data_inicio = data_inicio
        self.hora_inicio = hora_inicio
        self.data_fim = data_fim
        self.hora_fim = hora_fim

        tabela_sql_producao = Maquinas_Tabelas(self.maquina_selecionada).lista_tabelas_sql()[0][0]
        tabela_sql_resumo = Maquinas_Tabelas(self.maquina_selecionada).lista_tabelas_sql()[0][1]

        dicionario = {}

        dicionario['mostrar_cod_maquina'] = self.maquina_selecionada
        dicionario['mostrar_data_inicio'] = self.data_inicio
        dicionario['mostrar_hora_inicio'] = self.hora_inicio
        dicionario['mostrar_data_fim'] = self.data_fim
        dicionario['mostrar_hora_fim'] = self.hora_fim

        # mostrar_relogio_tempo_real
        # Este bloco é apenas para criar o relógio, depois apague o que for desnecessário
        valor_anterior = None
        tempo_atual_str = (time.strftime("%Y-%m-%d %H:%M:%S"))  # Aqui está em str
        tempo_atual_date = datetime.strptime(tempo_atual_str, "%Y-%m-%d %H:%M:%S")  # Aqui está em datetime
        # tempo_atras_date0 = datetime.strptime(tempo_atual_str, "%Y-%m-%d %H:%M:%S")
        tempo_atual_portug_str = datetime.strftime(tempo_atual_date, "%d/%m/%Y %H:%M:%S")
        if time.strftime("%Y-%m-%d %H:%M:%S") != valor_anterior:
            dicionario['mostrar_relogio_tempo_real'] = tempo_atual_portug_str[:16]
    
        # mostrar_hora_ultimo_ciclo
        conexao = Conexoes_SQL('cdtmes').obter_conexao()

        cursor = conexao.cursor()
    
        # Pegando todos os valores "Data, Hora" da tabela tabela_sql_producao
        comando_SELECT_tabela_sql_producao = (f"SELECT Data, Hora FROM {tabela_sql_producao}")
        cursor.execute(comando_SELECT_tabela_sql_producao)
        todos_valores_tabela_producao = cursor.fetchall()
    
        # Pegando todos os valores "temporarios" da tabela tabela_sql_resumo
        comando_SELECT_tabela_sql_resumo = (f"SELECT temporarios FROM {tabela_sql_resumo}")
        cursor.execute(comando_SELECT_tabela_sql_resumo)
        todos_valores_tabela_resumo = cursor.fetchall()
        # Decodificando os valores:
        todos_valores_temporarios_tabela_resumo_decodificados = []
        for item in todos_valores_tabela_resumo:
            todos_valores_temporarios_tabela_resumo_decodificados.append(str(item)[2:-4].split('•'))
        print("todos_valores_temporarios_tabela_resumo_decodificados:",
              todos_valores_temporarios_tabela_resumo_decodificados[-5:])
    
        cursor.close()
        conexao.close()
    
        valor_anterior = None
        if todos_valores_tabela_producao[-1:] != valor_anterior:

filme/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Criar Conta
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'imagens/fundo_azul.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                   {{ form|crispy }}
                </fieldset>
                <button class="bg-blue-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>Condutec</li>
        </ul>
    </footer>

{% endblock %}

filme/templates/detalhesfilme.html
{% extends 'base.html' %}

{% block titulo %}
HomeFilmes Hashflix
{% endblock %}


{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{ object.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.descricao|slice:":100" }}...
            </p>
            <div class="flex my-4">
                <a href="{{ object.episodios.first.video }}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left  items-center min-w-full  movie_lis">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }}
                    <br>
                    Visualizações: {{ object.visualizacoes }}
                </p>
            </div>

            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios
                </h2>
                {% for episodio in object.episodios.all %}
                    <h3 class='text-lg'>
                        <a href="{{ episodio.video }}">
                            <p>Episódio {{ forloop.counter }}: {{ episodio.titulo }}</p>
                        </a>
                    </h3>
                {% endfor %}
            </div>

        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                {% for filme in filmes_relacionados %}
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                            <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

</main>

{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil
{% endblock %}

{% block content %}

    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'imagens/fundo_azul.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">{{ user.username }}</h2>
            <form method="post">
               {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                  {{ form|crispy }}
                </fieldset>
                <button class="bg-blue-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>Condutec</li>
        </ul>
    </footer>



{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
(home) Sistema - CDT-MES
{% endblock %}

{% block head %}
<style>
    #id_email{
    width: 100%;
    color: #000000;
    padding: 5px 5px;
    }
</style>
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'imagens/fundo_azul.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <div class="card-group" style="flex: 1 1 15rem; background-color: transparent;">

              <div class="card" style="flex: 1 1 15rem; background-color: transparent; border-color: transparent;">
<!--                  https://drive.google.com/file/d/1TXU6_JGCbgzJ2wMZKna_00N0NrJ9bGHc/view?usp=drive_link-->
                  <a href="/pag_form_prod"><img src="https://drive.google.com/uc?id=1TXU6_JGCbgzJ2wMZKna_00N0NrJ9bGHc" class="card-img-top" alt="Imagem" style="object-fit: cover; height: 200px;"></a>
                <div class="card-body">
                  <h5 class="card-title" style="color: white;"><strong>Operacional</strong></h5>
                  <p class="card-text" style="color: white;">Confira informações da produção de uma máquina específica em tempo real.</p>
                    <br>
                  <a href="/pag_form_prod" class="btn btn-primary">Avançar</a>
                </div>
              </div>

              <div class="card" style="flex: 1 1 15rem; background-color: transparent; border-color: transparent;">
<!--                https://drive.google.com/file/d/1Ag3ag5MFGio2J_GV8RjG_-5AAg8ufYwY/view?usp=drive_link-->
                <a href="/dashboard"><img src="https://drive.google.com/uc?id=1Ag3ag5MFGio2J_GV8RjG_-5AAg8ufYwY" class="card-img-top" alt="Imagem" style="object-fit: cover; height: 200px;"></a>
                <div class="card-body">
                  <h5 class="card-title" style="color: white;"><strong>Dashboard 24Hr</strong></h5>
                  <p class="card-text" style="color: white;">Confira a produção bruta de todas as máquinas, com base na data atual.</p>
                  <br>
                  <a href="/dashboard" class="btn btn-primary">Avançar</a>
                </div>
              </div>

              <div class="card" style="flex: 1 1 15rem; background-color: transparent; border-color: transparent;">
<!--                https://drive.google.com/file/d/15PAb8_DyKPQ_cDyoKia7AU9fT-bn9AyQ/view?usp=drive_link-->
                <img src="https://drive.google.com/uc?id=15PAb8_DyKPQ_cDyoKia7AU9fT-bn9AyQ" class="card-img-top" alt="Imagem" style="object-fit: cover; height: 200px;">
                <div class="card-body">
                  <h5 class="card-title" style="color: white;"><strong>Apontar Perdas</strong></h5>
                  <p class="card-text" style="color: white;">Aponte a quantidade e motivo de todas as peças com não conformidade.</p>
                  <br>
                  <a class="btn btn-primary">Avançar</a>
                </div>
              </div>

              <div class="card" style="flex: 1 1 15rem; background-color: transparent; border-color: transparent;">
<!--                  https://drive.google.com/file/d/1OrrhUho7-UNcqNZ9pGuOdZUD5NykAhcE/view?usp=drive_link-->
                <img src="https://drive.google.com/uc?id=1OrrhUho7-UNcqNZ9pGuOdZUD5NykAhcE" class="card-img-top" alt="Imagem" style="object-fit: cover; height: 200px;">
                <div class="card-body">
                    <h5 class="card-title" style="color: white;"><strong>Inform. OP e Operador</strong></h5>
                    <p class="card-text" style="color: white;">Informe a ordem de produção atual e o nome do operador responsável.</p>
                    <br>
                    <a class="btn btn-primary">Avançar</a>
                </div>
              </div>

            </div>

        </div>
    </header>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2023</li>
            <li> Feito com Python (Django)</li>
            <li>Condutec</li>
        </ul>
    </footer>

{% endblock %}

filme/templates/pagina.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% load static %}
</head>
<body>
    <div class="card-body">
        <h5 class="card-title" id="mostrar_hora_ultimo_ciclo">{{ mostrar_hora_ultimo_ciclo }}</h5>
    </div>

    <script>
        $(document).ready(function(){
            setInterval(function(){
                $.ajax({
                    url: "{% url 'filme:sua_view' %}",
                    type: 'GET',
                    success: function(data) {
                        $('#mostrar_hora_ultimo_ciclo').html(data.mostrar_hora_ultimo_ciclo);
                    }
                });
            }, 1000); // tempo em milissegundos
        });
    </script>
</body>
</html>

filme/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}
Pesquisa de Filmes
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                  {% for filme in object_list %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                          <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                  {% endfor %}
                </div>


            </div>
        </section>
    </main>
{% endblock %}