filme/urls.py
# Definindo a url da homepage:

from django.urls import path, reverse_lazy
# Importando o objeto homepage
from .views import Homepage, Homefilmes, Detalhesfilme, Pesquisafilme, Paginaperfil, Criarconta, Pag_Form_Prod, Pag_Producao, Pag_Teste, dashboard, pagina, SuaView
from django.contrib.auth import views as auth_view

from django.urls import path
from .views import SuaView

app_name = 'filme'

urlpatterns = [
    # Chamando a função da View
    path('', Homepage.as_view(), name='homepage'),
    path('pag_form_prod/', Pag_Form_Prod.as_view(), name='pag_form_prod'),

    path('sua_view/', SuaView.as_view(), name='sua_view'),

    path('dashboard/', dashboard, name='dashboard'),
    path('pagina/', pagina, name='pagina'),
    path('pag_producao/', Pag_Producao.as_view(), name='pag_producao'),
    path('filmes/', Homefilmes.as_view(), name='homefilmes'),
    path('pag_teste/', Pag_Teste.as_view(), name='pag_teste'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('pesquisa/', Pesquisafilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html',
                                                             success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),
]

hashflix/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
# Incluindo o link do endereço da pagina do site que deseja exibir o app:
    path('', include('filme.urls', namespace='filme')),
]
# Adicionando na lista a configuração de link das imagens
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}
    {% endblock %}
</head>
<body class="bg-black text-gray-100 font-primary">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            if(scrollY>100){
                if(scrollY>window.innerHeight){
                nav.classList.add('invisible')
            }else{
                nav.classList.add('bg-gray-900')
                nav.classList.remove('invisible')
            }
            }else{
                nav.classList.remove('bg-gray-900')
                nav.classList.remove('invisible')
            }
        })
    </script>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>
</html>

templates/navbar.html
{% load static %}
<nav class="w-full flex justify-between items-center py-3 px-4 fixed z-50">
    <div class="w-4/12">
        <a href="/">
<!--            https://drive.google.com/file/d/1235Kcoj6ZpoT_bL_Etvb2X_mFgvPGBiH/view?usp=drive_link-->
            <img class="w-5/12" src="https://drive.google.com/uc?id=1235Kcoj6ZpoT_bL_Etvb2X_mFgvPGBiH">
        </a>
    </div>



    <div class="w-6/12 flex flex-nowrap justify-end">

<!--        {% if user.is_authenticated %}-->
<!--        <div class="mr-2">-->
<!--            <form method="get" action="{% url 'filme:pesquisafilme' %}">-->
<!--                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.GET.query }}" placeholder="Pesquisar...">-->
<!--                <input type="submit" value="">-->
<!--            </form>-->
<!--        </div>-->
<!--        {% endif %}-->

        <div class="mr-2">
            {% if user.is_authenticated %}
            <a href="{% url 'filme:logout' %}">
                <button class="bg-blue-600 text-white py-1 px-3 rounded-md">
                    Sair
                </button>
            </a>

            {% else %}
            <a href="{% url 'filme:login' %}">
                <button class="bg-blue-600 text-white py-1 px-3 rounded-md">
                    Login
                </button>
            </a>
            {% endif %}
        </div>

        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'filme:editarperfil' user.pk %}">
                <button class="bg-blue-600 text-white py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>
        </div>
        {% endif %}

    </div>


</nav>